spring:
  redis:
    host: 8.140.135.147
    port: 6380
    password: 123456
  datasource:
    url: jdbc:mysql://8.140.135.147:3306/cloudwear?useUnicode=true&characterEncoding=UTF-8
    password: 123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

swagger2:
  basePackage: com.com.cloudwaer.controller
  name: cloudwaer
  url: https://github.com/jiushiboy
  email: 1450495810@qq.com
  title: cloudwaer
  description: welcome to cloudwaer
  version: 2.0
  termsOfServiceUrl: www.cloudwaer.com

mybatis-plus:
  mapper-locations: classpath:**/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:   # 本地缓存实现
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote: # 远程缓存实现
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password:  ${spring.redis.password}