server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 8.140.135.147:8848 # 修改本机的host 文件
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # admin-service ADMIN-SERVICE  /admin-service/** -> 微服务（ADMIN-SERVICE）
      routes:
        - id: admin-service_router
          uri: lb://admin-service   # 转发到那个目的地
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1 # 当前端访问/admin/login - >login 将admin自动的去掉
        - id: article-service_router
          uri: lb://cloud-article   # 转发到那个目的地
          predicates:
            - Path=/article/**
          filters:
            - StripPrefix=1
    sentinel:
      transport:
        dashboard: localhost:8858
  redis:
    host: 8.140.135.147
    port: 6380


no:
  require:
    urls:
