server:
  port: 9999

spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: 8.140.135.147:8848
  datasource:
    url: jdbc:mysql://8.140.135.147:3306/cloudwear?useUnicode=true&characterEncoding=UTF-8
    password: 123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org:
      springframework:
        jdbc:
          core:
            StatementCreatorUtils: trace
